### ISSUE TITLE
Retrieve climate data through OGGM

### ISSUE THREAD

**Issue by JordiBolibar** [ODINN-SciML/MassBalanceMachine#11]
Right now we are directly downloading ERA5 data, with a region for the entire glacier dataset in a single .nc file. To be investigated if it would be better to move to the OGGM workflow. Advantages and disadvantages would be:

- We would have a .nc file per glacier, instead of a single .nc file for the whole region.
- We would have access to different climate products, not only ERA5.

**Comment by JulianBiesheuvel** [comment]
Currently, it is not possible to retrieve other climate variables other than precipitation and temperature, regardless of the climate product.  For now, we have decided to stick with the current workflow and let the user manually download the data from the Copernicus website, which also provides flexibility. This issue is closed for now.
